kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: rbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

